### ISSUE TITLE
Peer not discovered when using js-libp2p-kad-dht

### ISSUE THREAD

**Issue by iNDicat0r** [libp2p/go-libp2p-discovery#68]
Hi

I am using the advertise function:
```
discovery.Advertise(ctx, n.RoutingDiscovery, "FINDMEHERE")
```

and spin a few nodes. I also have a js implementation which uses the following code:
```
const bytes = new TextEncoder("utf8").encode("FINDMEHERE");
const hash = await multihashing(bytes, "sha2-256");
const cid = new CID(1, "raw", hash);
....
const providers = await all(node.contentRouting.findProviders(cid));
```

No provider is found. Is there any compatibility/spec issues between these libraries ?

**Comment by jacobheun** [comment]
This is an issue with the JS dht not implementing the latest specs. Closing this in favor of this issue you created there, https://github.com/libp2p/js-libp2p-kad-dht/issues/216.
